# Generated by Django 5.1.2 on 2024-11-06 08:35

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cubio_map', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GBIFData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('species', models.CharField(max_length=100)),
                ('occurrence_date', models.DateField()),
                ('coordinates', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('source_id', models.CharField(max_length=100, unique=True)),
            ],
        ),
    ]
