# Generated by Django 5.1.2 on 2024-11-07 12:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cubio_map', '0002_gbifdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='VegetationData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vegetation_index', models.DecimalField(decimal_places=2, max_digits=5)),
                ('capture_date', models.DateField()),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vegetation_data', to='cubio_map.area')),
            ],
        ),
    ]
