# Generated by Django 5.1.2 on 2024-11-27 08:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cubio_map', '0006_alter_userselectedarea_geom'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='user_selected_area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='cubio_map.userselectedarea'),
        ),
    ]
