# Generated by Django 5.1.2 on 2024-12-02 09:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cubio_map', '0006_alter_userselectedarea_geom'),
    ]

    operations = [
        migrations.CreateModel(
            name='AreaProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='area_project_images/')),
                ('initiated_by', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='planned', max_length=20)),
                ('date_initiated', models.DateField()),
                ('expected_duration', models.PositiveIntegerField(help_text='Duration in days')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='cubio_map.area')),
            ],
        ),
    ]
